clear EventIdx      ... 
LookPropMatrixPERC_H_PerTrial                    ...                         
LookPropMatrixPERC_PerTrial                       ...                        
LookPropMatrixRAW                      mocap_idx_rng        ...                 
LookPropMatrixRAW_H                    mocap_indices_per_trial   ...             
LookPropMatrixRAW_H_PerTrial           msg_index               ...               
LookPropMatrixRAW_PerTrial             new_t                   ...               
angular_orient                         new_t_ms                ...               
angular_vel                                       ...              
angular_vel_global                     old_t                  ...                
ans                                    pidx                   ...                
bad_eye                                              ...                
bb                                                   ...                
below_accelerometer_thresh                               ...                
below_ang_thresh                       plabels_x              ...                
below_thresh                           plabels_y              ...                
blockOrder                                            ...                 
condition                              ppp                   ...                 
conditionNum                           pupil                ...                  
condition_txt                          pval                ...                   
ctr                                    rho                 ...                   
eh_dat                                                     ...    
eh_dat_idx                                                 ...            
eh_dat_tmp                             t                  ...                    
exp_data                                                 ...            
eye_ang_x                                                ...
eye_ang_y                                              ...            
eye_data                               tmp             ...                       
eye_head_trial_and_condition_segments  tmp_idx_eye     ...                       
eye_idx_rng                            tmp_idx_mocap   ...                       
eye_index                              torso_angular_orient    ...               
f                                      torso_angular_vel           ...           
fix                                    torso_angular_vel_global   ...            
fixDat                                 torso_mocap_sixdof        ...             
fix_frame_binary                       trialNum            ...                   
fix_frames                             velFF              ...                    
fn1                                                    ...               
fn2                                                     ...              
head_mocap_sixdof                                                         ...
i                                                                     ...
interp_limit                           x5                                 ...    
interp_pupil                           x_lim                              ...    
interp_x                               xeye                               ...    
interp_y                               xxx                                ...    
j                                      y5                                 ...    
lim_list                               y_lim                              ...    
linear_pos                             yeye                               ...    
linear_vel                             yyy                          ...          
linear_vel_global                      ...
                             