%EYEVIZ eye data visualizer
%   EYEVIZ(ES, PS, TS) requires an eyeplot struct ES, pupilplot
%   struct PS, and timeplot struct TS. for more info see:
%      NEW_EYEPLOT_STRUCT
%      NEW_PUPILPLOT_STRUCT
%      NEW_TIMEPLOT_STRUCT

% $Id: eyeviz.m,v 1.4 2001/08/17 19:24:16 pskirko Exp $
% pskirko 6.21.01

function eyeviz(eyeplot_struct, pupilplot_struct, timeplot_struct)

% ############ GUI #############

h = figure;
set(h, 'Tag', 'ev_figure', 'Renderer', 'painters', 'DoubleBuffer', ...
       'on');


% ############ DATA ##############

setappdata(h, 'ev_eyeplot_struct', eyeplot_struct);
setappdata(h, 'ev_pupilplot_struct', pupilplot_struct);
setappdata(h, 'ev_timeplot_struct', timeplot_struct);


% ############ BACK TO GUI #############

h_ea = axes('Parent', h, ...
	    'NextPlot', 'replacechildren', ...
	    'Position', [0.06 0.32 0.92 0.56], ...
	    'Tag', 'ev_eyeplot_axes');

h_pa = axes('Parent', h, ...
	    'NextPlot', 'replacechildren', ...
	    'Position', [0.06 0.06 0.20 0.20], ...
	    'Tag', 'ev_pupilplot_axes');

h_ta= axes('Parent', h, ...
	   'ButtonDownFcn', 'eyeviz_cb([''goto_time''])', ...
	   'NextPlot', 'replacechildren', ...
	   'Position', [0.34 0.06 0.64 0.20], ...
	   'Tag', 'ev_timeplot_axes');


% context menu for eyeplot axes
h_ec = uicontextmenu;
uimenu(h_ec, 'Label', 'change x and y limits', ...
       'Callback', 'eyeviz_cb(''eyeplot_change_xy_lim'')', ...
       'Tag', 'ev_eyeplot_change_xy_lim_menu');
set(h_ea, 'UIContextMenu', h_ec);

% context menu for timeplot axes
h_tc = uicontextmenu;

uimenu(h_tc, 'Label', 'change t step', ...
       'Callback', 'eyeviz_cb(''timeplot_change_t_step'')', ...
       'Tag', 'ev_timeplot_change_t_step_menu');
uimenu(h_tc, 'Label', 'change x limits', ...
       'Callback', 'eyeviz_cb(''timeplot_change_x_lim'')', ...
       'Tag', 'ev_timeplot_change_x_lim_menu');
uimenu(h_tc, 'Label', 'change y limits', ...
       'Callback', 'eyeviz_cb(''timeplot_change_y_lim'')', ...
       'Tag', 'ev_timeplot_change_y_lim_menu');
set(h_ta, 'UIContextMenu', h_tc);

% prev button
uicontrol(h, 'Style', 'pushbutton', ...
	  'Callback', 'eyeviz_cb(''prev'')', ...
	  'Units', 'normalized', ...
	  'Position', [0.02 0.90 0.08 0.08], ...
	  'String', 'prev', ...
          'Tag', 'ev_prev');

% next button
uicontrol(h, 'Style', 'pushbutton', ...
	  'Callback', 'eyeviz_cb(''next'')', ...
	  'Units', 'normalized', ...
	  'Position', [0.10 0.90 0.08 0.08], ...
	  'String', 'next', ...
          'Tag', 'ev_next');

% trail button
uicontrol(h, 'Style', 'pushbutton', ...
	  'Callback', 'eyeviz_cb(''trail'')', ...
	  'Units', 'normalized', ...
	  'Position', [0.26 0.90 0.08 0.08], ...
	  'String', 'trail', ...
          'Tag', 'ev_trail');

% new fixation button
uicontrol(h, 'Style', 'pushbutton', ...
	  'Callback', 'eyeviz_cb(''new_fix'')', ...
	  'Units', 'normalized', ...
	  'Position', [0.34 0.90 0.08 0.08], ...
	  'String', 'new fix', ...
          'Tag', 'ev_new_fix');

% edit fixation
uicontrol(h, 'Style', 'pushbutton', ...
	  'Callback', 'eyeviz_cb(''edit_fix'')', ...
	  'Units', 'normalized', ...
	  'Position', [0.42 0.90 0.08 0.08], ...
	  'String', 'edit fix', ...
          'Tag', 'ev_edit_fix');


uicontrol(h, 'Style', 'text', ...
	  'Units', 'normalized', ...
	  'Position', [0.74 0.90 0.24 0.08], ...
	  'String', '', ...
          'Tag', 'ev_time_text');

% go button AND initialize gui
% for this reason keep this last on the page
uicontrol(h, 'Style', 'pushbutton', ...
	  'Callback', 'eyeviz_cb(''jump'')', ...
	  'Units', 'normalized', ...
	  'Position', [0.18 0.9 0.08 0.08], ...
	  'String', 'jump', ...
	  'CreateFcn', 'eyeviz_cb(''init'')', ...
          'Tag', 'ev_jump');